spring.application.name=Dairy Farm Management System

PSQL_DATABASENAME=dairy_farm_management
PSQL_USERNAME=postgres
PSQL_USERPASSWORD=password

spring.datasource.url=jdbc:postgresql://localhost:5432/${PSQL_DATABASENAME}
spring.datasource.username=${PSQL_USERNAME}
spring.datasource.password=${PSQL_USERPASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

client-id = DairyFarmManagement
issuer-uri = http://localhost:9090/realms/DairyFarmManagementSystem
client-secret = 7OUYg0dfRoPbgNN5KYIS2ETEuvjvxWpu
audience = account
spring.security.oauth2.resourceserver.jwt.issuer-uri=${issuer-uri}
spring.security.oauth2.resourceserver.jwt.audiences=${audience}